#ifndef COLORS_H
#define COLORS_H

#include <Adafruit_ST7735.h>

// ===== COLORES BÁSICOS =====
#define COLOR_BG          ST77XX_BLACK
#define COLOR_TEXT        ST77XX_WHITE

// ===== COLORES PRINCIPALES =====
#define COLOR_PRIMARY     ST77XX_BLUE
#define COLOR_SECONDARY   ST77XX_MAGENTA
#define COLOR_SUCCESS     ST77XX_GREEN
#define COLOR_WARNING     ST77XX_YELLOW
#define COLOR_DANGER      ST77XX_RED
#define COLOR_INFO        ST77XX_CYAN

// ===== ESTADOS =====
#define COLOR_RUNNING     ST77XX_GREEN
#define COLOR_PAUSED      ST77XX_YELLOW
#define COLOR_BREAK       ST77XX_CYAN
#define COLOR_IDLE        ST77XX_WHITE

// ===== MENU =====
#define COLOR_MENU_TEXT   ST77XX_WHITE
#define COLOR_MENU_SELECT ST77XX_BLUE

#endif