#ifndef SETTINGS_H
#define SETTINGS_H

// ===== TIMING CONFIGURATION =====
#define UI_REFRESH_MS 300
#define DEBOUNCE_MS 50
#define LONG_PRESS_MS 1000
#define POT_SAMPLES 5
#define POT_THRESHOLD 10  // ⭐ AGREGADO

// ===== POMODORO DEFAULTS =====
#define DEFAULT_POMODORO_TIME 1500
#define DEFAULT_SHORT_BREAK 300
#define DEFAULT_LONG_BREAK 900
#define POMODOROS_UNTIL_LONG 4

// ===== GYM DEFAULTS =====
#define DEFAULT_GYM_SERIE_DURATION 1000
#define DEFAULT_GYM_TARGET_SERIES 10

// ===== TASK TIMER DEFAULTS =====
#define DEFAULT_TASK_TIME 1800

// ===== SENSOR THRESHOLDS =====
#define SOUND_THRESHOLD 2000
#define SOUND_COOLDOWN_MS 500
#define CLAP_DURATION_MIN 50   // ⭐ AGREGADO
#define CLAP_DURATION_MAX 300  // ⭐ AGREGADO
#define CLAP_COOLDOWN_MS 500   // ⭐ AGREGADO

// ===== LED TIMING =====
#define LED_BLINK_SLOW_MS 1000   // ⭐ AGREGADO
#define LED_BLINK_FAST_MS 250    // ⭐ AGREGADO

// ===== BUZZER CONFIG =====
#define BUZZER_FREQ 2000
#define BUZZER_FREQ_MED 2300     // ⭐ AGREGADO
#define BUZZER_DURATION 100

#endif